#!/usr/bin/env python3

"""Simple BBC Micro disassembler handling Micropower Chess computed jump
and inserting some comments about that Chess program's workings.

Silas S. Brown - public domain - no warranty

Micropower Chess is proprietary software.  To respect the
original author's copyright, this disassembler does NOT
contain or redistribute any game code or assets.

To use this tool, you must supply your own copy of the
original Micropower Chess binary: I am assuming anyone who
is interested in Micropower Chess will have a copy of it in
their legitimate collection of disks from the 1980s.

This program simply reads your local file and overlays my
original analytical comments for educational and historical study.

"""

chess_disk = "chess.ssd"
load_from_sector = 0x21
binary_size = 0x2280
loadTo = 0xE00 # loads at 1E00 but relocates to E00
entryPoint = 0x3000 # disk version's relocator (runs at 0x4000, then calls 1C00)

def main():
    data=open(chess_disk,"rb").read()[load_from_sector*256:load_from_sector*256+binary_size]
    mem = bytearray(loadTo+len(data))
    for i in range(len(data)): mem[loadTo+i] = data[i]
    lines = disasm(mem)
    with open("chess.asm","w") as f:
        for addr in sorted(lines.keys()):
            f.write(lines[addr] + "\n")
    print(f"Wrote {len(lines)} lines to chess.asm")

comments = {
    0x0E00:"tokenised BASIC CALL for tape version CHAIN to work",
    0x0E20:"start of pawn sprite",
    0x0E70:"start of knight sprite",
    0x0EC0:"start of bishop sprite",
    0x0F10:"start of rook sprite",
    0x0F60:"start of queen sprite",
    0x0FB0:"start of king sprite",
    0x1000:"additions for diagonal movement on a 10x12 board",
    0x1004:"additions for straight movement",
    0x1008:"additions for knight moves",
    0x1010:"additions for White pawn moves (incl captures) (first two identical: pawn handler uses direction)",
    0x1014:"additions for Black pawn moves (incl captures)",
    0x1018:"LSB address of Black pawn moves",
    0x1019:"LSB address of White pawn moves",
    0x101A:"LSB address of knight moves",
    0x101B:"LSB addresses of bishop, rook, queen, king directions",
    0x101F:"number of possible moves of Black pawn",
    0x1020:"number of possible moves of White pawn",
    0x1021:"number of possible moves of knight",
    0x1022:"number of directions of bishop, rook, queen, king",
    0x1026:"material values table",
    0x102C:"initial back-rank pattern (shows piece IDs)",
    0x1034:"Space reserved for 120-byte board: 10x12 including $FF borders (two rows of $FF above and below; 1 column after + before, effectively acting as 2). This gets wiped and reinitialised on load, so they could have put a 120-byte secret message here if they wanted. As it is, they left a board with a few moves played: might have been used with the init bypassed during testing. NB the memory listing is \"upside down\": board is displayed from screen bottom, so the *white* pieces start with lower RAM addresses.", # board goes all the way to 10AC
    0x10AC:"white pieces total and per-type attack/defence count",
    0x10B3:"black pieces total and per-type attack/defence count",
    0x10BA:"space for attacks list (direction + pinned-piece pairs) filled for one piece at a time during evaluation",
    0x10CE:"start of royal piece list (squares kings and queens are on)",
    0x1107:"opening book moves (white e4 or d4, black e5 or d5, 3 bytes each)",
    0x1115:"table of piece IDs to ASCII letters for analysis edit mode",
    0x111C:"start of space reserved for evaluation move list (appears to be initialised for testing)",
    0x1480:"still space reserved for move list; I think we periodically switch between 00 and FF blocks to protect against tape-read glitches (again they could have left a secret message here?); it goes up to 18FA",
    0x1500:"space reserved for user move list (appears to be initialised for testing), can also be overspill for evaluation list",
    0x1900:"start of separate space for 'saved' board in the analysis option, initially set to the starting position (again plotted from the bottom so white pieces lower in memory)",
    0x194E:"start space for backup board used for user-takeback",
    0x19A0:"Demo data (Fischer-Spassky game 6).  This is overwritten by Replay data when a game is played.  First 2 bytes point to next free slot, then start and destination squares as 10*(rank+1)+file where rank and file start at 1; for castling the king moves first and then rook after a byte 01.",
    0x1A50:"Space for more Replay moves if you have a game longer than the Fischer-Spassky",
    0x1A80:"Still space for more Replay moves; I think we periodically switch between 00 and FF blocks to protect against tape-read glitches (again they could have left a secret message here?) It goes right up to 1C00 giving you 303-ply (with castling counting as 2.5-ply); I saw display bugs if you go over ~260-ply with an unfinished game but not yet seen why in the code",
    0x1C00:"main entry point",
    0x1C03:"main menu jump point",
    0x1C05:"fully clear clock string",
    0x1C17:"$10 is the MSB for a few indirect pointers",
    0x1C19:"and this is a loop to initialise $8B through $9F at stride 2 to that $10",
    0x1C1F:"Mode 1, set palette (second VDU19 is unnecessary), turn off cursor and print main menu",
    0x1C66:"p (play)",
    0x1C6A:"a (analysis)",
    0x1C71:"q (quit)",
    0x1C75:"so 'quit' means simulate a Ctrl-Break (we can't just RTS to BASIC after messing up its 0-page so much)",
    0x1C78:"r (replay)",
    0x1C7F:"b (blitz)",
    0x1C81:"none of the above = go back and wait for another keystroke",
    0x1C83:"set blitz=True (any non-0 value, $62 in this case)",
    0x1C85:"main menu Play entry point",
    0x1C87:"set replay move pointer to $(19)A2 i.e. clear list",
    0x1C8A:"and a copy here",
    0x1C8D:"and the MSB",
    0x1C9F:"start with move number = 1",
    0x1CA6:"main play loop",
    0x1CA9:"check if computer plays white (0) or black ($80)",
    0x1CAB:"if black, let user go first",
    0x1CBC:"increment move number",
    0x1CC1:"ask for destination coordinates",
    0x1CC3:"dash (-)",
    0x1CC6:"get keypress, lower-case and print",
    0x1CCB:"immediate return if lower than digits",
    0x1CCF:"or higher than capital letters",
    0x1CD1:"convert to lower case",
    0x1CD6:"and return it",
    0x1CD7:"get keypress intercept Escape",
    0x1CDA:"Escape pressed?",
    0x1CDC:"if not, return character we read",
    0x1CDE:"clear the Escape condition",
    0x1CE6:"check key while clock running",
    0x1CE8:"osbyte $81 = INKEY, 10 centiseconds (0.1s) doubles as the clock timer",
    0x1CF1:"handles Escape",
    0x1CF6:"handles normal keypresses",
    0x1CF8:"tenths of a second column",
    0x1D04:"are we in Blitz mode?",
    0x1D06:"if not, don't have to move at 10secs",
    0x1D08:"strip inside-user's-turn return address from stack",
    0x1D09:"so it goes back to play loop and takes another computer turn",
    0x1D29:"read text cursor position",
    0x1D2E:"save cursor position",
    0x1D41:"dot (.) to separate seconds from tenths",
    0x1D4C:"print last clock digit and restore cursor position",
    0x1D51:"position cursor",
    0x1D5E:"print space and two clock digits",
    0x1D63:"print next two clock digits",
    0x1D64:"we use the top of the function keys area at 0BDF for clock readout string",
    0x1D6A:"print next clock digit",
    0x1D71:"clear clock string",
    0x1D7C:"roll clock counter column to 0 and advance next col",
    0x1D82:"advance clock column",
    0x1D85:"make sure there's a digit there",
    0x1D95:"inline string print",
    0x1D96:"get return address",
    0x1D99:"and store it as string address",
    0x1D9F:"branch always taken as Y=0 on init",
    0x1DA8:"($37 has wrapped to 0 if we get here)",
    0x1DAA:"load next character (Y=0 throughout, 6502 just didn't have a version that doesn't use X or Y)",
    0x1DAC:"go back and write it if high bit not set",
    0x1DB0:"continue execution after the string",
    0x1DCB:"'w'",
    0x1DCF:"'b'",
    0x1DD1:"loop until we get 'w' or 'b'",
    0x1DD3:"user plays black, computer plays white",
    0x1DD7:"user plays white, computer plays black",
    0x1DD9:"store computer's colour in $68",
    0x1DDB:"check for blitz",
    0x1DDF:"force level 1 (no time to calculate more in blitz)",
    0x1DF2:"Default level number is 2 unless",
    0x1DF4:"input is less than '7' and",
    0x1DF8:"greater than or equal to '1'",
    0x1DFE:"in which case use inputted level instead",
    0x1DFF:"6F holds the level number",
    0x1E02:"board setup",
    0x1E08:"so ($60,$61) -> $1034 (the 10x12 board with borders)",
    0x1E0A:"write 120 x FF bytes to erase the board",
    0x1E15:"so ($60,$61) -> $102C (initial back-rank pattern)",
    0x1E1D:"to store this piece on White's back rank",
    0x1E21:"and change its colour to Black",
    0x1E23:"to be stored on Black's back rank",
    0x1E27:"put a pawn in front of it as well",
    0x1E29:"for White",
    0x1E2D:"and a Black pawn",
    0x1E2F:"for Black",
    0x1E33:"and set the intervening squares to empty",
    0x1E35:"on the 6th rank",
    0x1E39:"and the 5th rank",
    0x1E3D:"and the 4th rank",
    0x1E41:"and the 3rd rank",
    0x1E4A:"initialise royal piece list",
    0x1E4C:"initial White King square",
    0x1E4E:"writes to $10CE, since ($60,$61) has had 8 increments since $102C so it's $1034 and we set Y to $9A",
    0x1E51:"initial Black King square",
    0x1E56:"initial White Queen square",
    0x1E5A:"initial Black Queen square",
    0x1E60:"clear screen and draw board",
    0x1E62:"CLS",
    0x1E65:"draw board",
    0x1E9E:"plot square",
    0x1EB2:"set square colour/position",
    0x1ED7:"($60, $61) -> screen memory location of square",
    0x1EDD:"draw piece on square",
    0x1EE4:"A is now $67*10",
    0x1EE5:"rank*10+file",
    0x1EE8:"read board square (skipping top border)",
    0x1EEF:"no piece to draw -> return",
    0x1EF1:"X is now the piece type",
    0x1EF2:"sprite addr MSB: we'll increment it at least once to 0E",
    0x1EF9:"each sprite is $50 bytes",
    0x1F02:"($62,$63) -> sprite",
    0x1F12:"jump if we need to flip the sprite's colour to black",
    0x1F18:"effectively a JMP (the OR won't ever be 0 as background squares are red and green)",
    0x1F20:"write to screen memory",
    0x1F34:"update clock",
    0x1F51:"call Your move",
    0x1F7B:"clear 5 lines and position cursor",
    0x1F86:"move cursor to line 12",
    0x1F8E:"erase a line",
    0x1FA2:"user's turn",
    0x1FA8:"delete (the take-back key)",
    0x2009:"validate user's move",
    0x200F:"load computer's colour",
    0x2011:"and flip it",
    0x2013:"to get the colour of the side to validate",
    0x2017:"9x is Econet workspace, assumed not in use",
    0x201B:"($9E,$9F) -> $10DD",
    0x2023:"($5E,$5F) -> $1500",
    0x2075:"delay loop",
    0x2079:"shorter delay loop",
    0x20AB:"check for Check",
    0x20CA:"generate attacks for current square",
    0x2114:"restore and return",
    0x218A:"check mode of attack scan",
    0x218C:"mode 7 = don't just stop at first attacking piece (see if more are doubled up behind it)",
    0x218E:"(don't need to do this when just checking for Check)",
    0x21AE:"generate legal moves",
    0x21D5:"read board[square] at $1034+square (as 8B is $10)",
    0x21F0:"check occupancy after moving square pointer",
    0x21F2:"(returns A: 0=empty, 1=enemy, 2=friendly, 3=border; leaves piece type in $94)",
    0x220F:"return 1 for enemy",
    0x2212:"return 2 for friendly",
    0x2215:"return 3 for border",
    0x2218:"increment per-colour attack/defence counters",
    0x222D:"($60,$61) -> $10AC",
    0x2231:"see if it's a Black piece",
    0x2235:"use the $10B3 block instead",
    0x2239:"piece type",
    0x223F:"override piece type to queen if $62 is telling us to scan in queen mode (not sure what sets this)",
    0x2241:"per-type offset",
    0x224E:"add 1 to count",
    0x2256:"lower nibble stores first recorded piece value",
    0x225C:"upper nibble stores the second",
    0x2260:"? we don't handle more than 2 pieces of same type attacking one square: mostly OK as this program doesn't support underpromotion and queens are special-cased, but we don't enforce this on the analysis board?",
    0x2262:"(effectively a JMP since we won't wraparound)",
    0x2266:"fetch material value from $1025 + piece type (in $94)",
    0x226B:"shift into upper nibble",
    0x2271:"and OR it into the lower nibble",
    0x2282:"suppress defensive contribution of any pinned piece shielding a royal piece",
    0x2291:"($60,$61) -> $10BA (attacks list)",
    0x22C8:"make a move",
    0x22DA:"read board[square] at $1034+square (as 8B is $10)",
    0x22F2:"set has-moved flag (used by evaluator's development bonuses and early-move penalties)",
    0x2347:"set has-castled flag (used by evaluator's castling bonus)",
    0x2353:"generate moves for piece",
    0x2355:"keep just colour and piece type, not flags",
    0x2357:"Black pawn = only Black piece moving different from White",
    0x235B:"use 0 for Black pawn",
    0x235F:"otherwise piece type 1-6",
    0x2363:"$101F + piece = possible moves or directions",
    0x2369:"$1018 + piece = LSB (MSB $10) of moves/directions to read",
    0x2371:"loads the board-square offset of a move or direction",
    0x237C:"is it friendly piece (2) or border (3)?",
    0x237E:"stop looking if either",
    0x2380:"see if it's an empty square",
    0x2382:"and save flag for later",
    0x2383:"load piece type (0 if Black pawn)",
    0x2387:"go to pawn handler if pawn",
    0x238D:"if it wasn't an empty square, stop here",
    0x2391:"are we moving the king?",
    0x2393:"if so, stop here (king can go only 1 square)",
    0x2395:"are we moving anything 'less than' a bishop (this is why knights must come before bishops)",
    0x2397:"if bishop or higher, go back and check next square in same direction",
    0x2399:"wrap up for this direction",
    0x239F:"go back if there's more directions to check",
    0x23A3:"are we moving the king?",
    0x23AB:"pawn move handler (move/capture is different)",
    0x23AD:"check pawn move type from move-table pointer",
    0x23AF:"a capturing pawn move",
    0x23B1:"a 'forward two' pawn move (if gets here, already checked we're on first rank etc)",
    0x23B3:"forward-one: get the 'was it an empty square' flag",
    0x23B4:"can't do it if blocked",
    0x23B6:"find out if we're on a promotion square",
    0x23C2:"set bit 5 to queen it (underpromotion not supported)",
    0x23D1:"go back and see if we can also move forward two",
    0x23D3:"effectively a JMP to wrap up",
    0x23D5:"get the 'was it an empty square' flag",
    0x23D6:"can't do it if blocked",
    0x23DE:"pawn capture: get the 'was it an empty square' flag",
    0x23DF:"if empty, might still be able to go there if en-passant",
    0x23E9:"go to make the move",
    0x23ED:"set promotion flag (bit 5) if we're queening it while capturing",
    0x23F1:"effectively a JMP to make the move",
    0x23F9:"append to move list",
    0x23FB:"don't let move list grow past $18F8",
    0x23FD:"<$18, fine",
    0x23FF:">$18 (I don't think this can happen)",
    0x2401:"=$18 so check LSB",
    0x2407:"load current free slot (?)",
    0x2411:"6 bytes: next (LSB MSB) (I think?), from square, to square, flags (bit4=first move of piece, bit5=promotion-zone, bit6=en-passant/castling?), eval score",
    0x2445:"each move record is 6 bytes",
    0x2451:"handle move list full: write terminator and return",
    0x245A:"en-passant availability check",
    0x245E:"White pawn: already on the relevant rank; Black pawn: adjust forward one rank",
    0x2461:"Black pawn: add one rank so both cases can be tested against the 5th rank",
    0x2463:"both cases now require the adjusted square to be on the 5th rank",
    0x246A:"(can't do it if we're not)",
    0x246C:"check previous ply's flag byte at record offset 4",
    0x2470:"was it the first move of that piece?",
    0x2472:"(can't take en passant if wasn't)",
    0x2481:"check the piece that moved was in fact a pawn",
    0x2483:"can't do en-passant if it wasn't a pawn that moved",
    0x2491:"previously-moved pawn must be exactly 1 rank away from capturing square",
    0x2493:"(can't do it if not)",
    0x2497:"set bit 6: tells 'make a move' to process the extra record",
    0x249E:"add the \"also make the captured pawn disappear from its forward-two square\" record",
    0x24B3:"combine last two move records", # also JSR'd to from castling
    0x24B5:"(this move has 2 records when made but counts as 1 in move list)",
    0x24C7:"castling availability check",
    0x24C9:"make sure king hasn't already moved",
    0x24CE:"make sure side to move is not in check",
    0x24D0:"(can't castle out of check)",
    0x24D2:"start with kingside castling",
    0x24D4:"castling scan direction rook-to-king = -1",
    0x24D6:"king to rook is +3 for kingside",
    0x24DF:"now looking at rook square",
    0x24E5:"check what's there on the board,",
    0x24E7:"strip colour, but keep has-moved flag,",
    0x24E9:"and make sure it's an unmoved rook",
    0x24EB:"if not, can still check castling queenside",
    0x24F1:"scan intervening square",
    0x24F5:"can't castle through non-empty square (but can still scan queenside)",
    0x24F7:"the square we're scanning",
    0x24F9:"b1",
    0x24FB:"skip attack check",
    0x24FD:"b8",
    0x24FF:"skip attack check",
    0x2504:"can't castle through check (but can still scan queenside)",
    0x2509:"scan toward the king using the direction we set",
    0x250F:"back to scan next intervening square",
    0x2512:"move king one square towards rook (opposite to scan direction)...",
    0x2515:"...and another",
    0x2519:"and set bit 6 in flags to indicate another part of the move is coming",
    0x2532:"(not sure why we don't just go to 24AF which does the 8E to 8A for us as well)",
    0x253D:"finished scanning both castling directions",
    0x253F:"for queenside castling,",
    0x2541:"scan direction rook-to-king is +1",
    0x2543:"and offset from king to rook is -4",
    0x2547:"go back and see if we can also castle queenside",
    0x254A:"take back a move",
    0x257C:"write board[square] at $1034+square (as 8B is $10)",
    0x25E8:"record and display move (?)",
    0x2620:"show and list move (?)",
    0x2622:"beep",
    0x2647:"append bytes to replay data",
    0x2685:"convert square to coordinates",
    0x2691:"print coordinates",
    0x269F:"computer's turn",
    0x26CA:"branch if we need to call out castling or en passant",
    0x26D1:"dash (-)",
    0x26DE:"kingside castling?",
    0x26ED:"queenside castling?",
    0x272D:"main menu Analysis entry point",
    0x274F:"read board[square] at $1034+square (as 8B is $10)",
    0x275E:"Delete",
    0x2762:"dot (.) to finish board entry",
    0x2766:"Return (leave square unchanged)",
    0x2771:"($60,$61) -> $1114, just before piece-letter table",
    0x2773:"scan piece-letter table",
    0x2798:"write board[square] at $1034+square (as 8B is $10)",
    0x27A5:"(effectively a JMP)",
    0x27A7:"analysis Delete handler",
    0x27B3:"analysis Finish handler",
    0x27C1:"'n'",
    0x27C5:"(effectively a JMP)",
    0x27D6:"'y'",
    0x27E0:"CLS",
    0x27E8:"set move number to 2 (skips opening book)",
    0x27FF:"'w'",
    0x280C:"check if computer plays white (0) or black ($80)",
    0x280E:"and branch to who should play black",
    0x283F:"handle user takeback",
    0x286E:"read board[square] at $1034+square (as 8B is $10)",
    0x2890:"opening book logic",
    0x289B:"($5A,$5B) -> $1105 (2 bytes before 1st opening book move e4)",
    0x289D:"check if we're playing Black",
    0x289F:"jump to Black opening logic if so",
    0x28A1:"as White, check vertical sync frames as source of randomness (may not work on all emulators)",
    0x28A6:"keep e4 opening",
    0x28A8:"increment opening book pointer to play d4 (or, via jump, d5 as Black)",
    0x28AF:"advance two 3-byte opening-book entries to reach Black's replies",
    0x28BD:"check where White moved from",
    0x28BF:"b1 knight moved?",
    0x28C1:"to increment opening book pointer to play d5",
    0x28C3:"g1 knight moved?",
    0x28C5:"ditto",
    0x28C7:"d2 pawn moved?",
    0x28C9:"ditto",
    0x28CB:"if a, b or c pawn moved, just return (plays e5)",
    0x28CD:"e2 pawn moved? (if so, we also play e5)",
    0x28CF:"increment opening book pointer to d5 if f, g or h pawn moved",
    0x28EB:"save analysis board",
    0x28F6:"($62,$63) = write pointer -> 18FF (saves board at 1900) or, via jump, 194D (for backup board at 194E)",
    0x2901:"save backup board for user takeback",
    0x2907:"(effectively a JMP)",
    0x2909:"calculate computer move",
    0x290B:"are we on move 1?",
    0x2920:"($5E,$5F) -> $111C (lower than the $1500 we set it to when generating user's legal moves)",
    0x2936:"load the level number",
    0x2955:"iterative search-node entry point",
    0x2957:"($70 is ply depth from root)",
    0x2960:"compare searched depth with level",
    0x2962:"if at max ply, skip move ordering (no point sorting moves we won't recurse past)",
    0x2967:"walk ordered legal moves",
    0x296F:"'read next move record' loop",
    0x297A:"second byte of move record is 0 -> end of list",
    0x297C:"copy move to stack",
    0x298D:"depth vs level number check",
    0x298F:"non-leaf: don't need extra king-safety verify",
    0x2997:"0 = not putting ourselves in check",
    0x299F:"test if depth==level",
    0x29A5:"are we giving check?",
    0x29A9:"check for Check on the side about to move",
    0x29AC:"not a checking move: terminal leaf",
    0x29AE:"Check extension: search one more ply",
    0x29B0:"reuse legality flag already computed for interior nodes",
    0x29B4:"score 0 (own king in check) skip",
    0x29B9:"flip side to move ($69)",
    0x29BF:"check colour of side to move",
    0x29C1:"skip move increment if it's Black to move",
    0x29C3:"increment move number",
    0x29C5:"copy node forward, opening slot before it",
    0x29D2:"handle stalemate/checkmate/backtrack",
    0x29D4:"if moves found, skip no-moves logic",
    0x29D6:"No moves. Was side to move in check?",
    0x29D8:"If yes, jump to checkmate",
    0x29DA:"stalemate scores 128/255",
    0x29DC:"(effectively a JMP)",
    0x29DE:"checkmate found at this move number",
    0x29E0:"record it",
    0x29E2:"and score 255/255",
    0x29E4:"(effectively a JMP)",
    0x29E6:"check if at root",
    0x29E8:"with move list exhausted,",
    0x29EC:"if so, tree search is finished",
    0x2A00:"load this node's score",
    0x2A02:"push the move score",
    0x2A05:"mark this node has moves (not mate)",
    0x2A0A:"compare score with parent's best",
    0x2A0C:"for pruning",
    0x2A20:"if we're at root",
    0x2A22:"(i.e. depth==1)",
    0x2A26:"then move we found is new best-so-far",
    0x2A28:"so keep it",
    0x2A2E:"check if best root move",
    0x2A31:"is a forced mate",
    0x2A35:"if found forced mate, shorten search horizon by 2 plies for rest of game (won't get here if level is 1)",
    0x2A37:"(Bug: if user undoes a move that let computer see mate, rest of game gets 2 fewer search plies)",
    0x2A39:"parity correct mate move number from side to play",
    0x2A3F:"it's mate one move sooner",
    0x2A48:"main menu Replay entry point",
    0x2ADB:"replay clear from-square (?)",
    0x2AF1:"check for Check and mates",
    0x2AF5:"earlier found mate at this move number",
    0x2AF8:"is it the current move number?",
    0x2AFA:"if not, no mate yet",
    0x2B05:"was it computer or user that won?",
    0x2B09:"looks like it was computer",
    0x2B63:"call check",
    0x2B6F:"call mate",
    0x2B7C:"unmake move in search",
    0x2B7E:"start by flipping colour of side to move",
    0x2B82:"check colour of the ply after the undo",
    0x2B84:"if White, skip move number decrement",
    0x2B86:"it's Black so we're undoing White's move: decrement move number",
    0x2B8E:"decrement ply-depth counter",
    0x2BAD:"insertion-sort move-list by static eval",
    0x2C23:"evaluate candidate move",
    0x2C2B:"putting ourselves in check breaks the rules",
    0x2C2D:"and scores 0",
    0x2C2F:"(effectively a JMP to skip evaluating putting ourselves in check)",
    0x2C3A:"clear attacks list",
    0x2C4B:"build royal-piece attacks",
    0x2C4D:"attack count = 0",
    0x2C55:"pointer = royal piece list",
    0x2C60:"$FF terminates the royal piece list",
    0x2C6D:"8 directions to scan",
    0x2C8A:"empty square: keep scanning",
    0x2C8C:"reached border?",
    0x2C8E:"advance to next scan direction",
    0x2C90:"friendly piece?",
    0x2C92:"remember it in $90 (potential pin screen) and keep scanning behind it",
    0x2C9B:"enemy piece found: can it actually attack the royal piece?",
    0x2C9D:"enemy queen vs our queen: special case",
    0x2CA4:"enemy piece type vs royal piece type: check if attack is valid",
    0x2CC2:"store first friendly piece",
    0x2CC4:"and continue to scan for an attacker behind the friendly piece as we're looking after a royal piece",
    0x2CC7:"queen-attacks-queen special case",
    0x2D07:"attack direction",
    0x2D0D:"pinned piece square (?)",
    0x2D1D:"static evaluator",
    0x2D1F:"material = 0",
    0x2D21:"positional = 0",
    0x2D23:"best capture value = 0 (?)",
    0x2D25:"highest attack = 0 (?)",
    0x2D27:"second-highest attack = 0 (?)",
    0x2D29:"move-target-is-hanging flag = 0",
    0x2D2B:"attack-check mode = thorough",
    0x2D35:"load board[square]",
    0x2D39:"is it a border?",
    0x2D3E:"piece data (with colour)",
    0x2D42:"piece type (without colour)",
    0x2D46:"pawn: skip positional checks",
    0x2D4A:"knight or bishop: development check",
    0x2D4E:"king: safety check (?)",
    0x2D50:"if gets here, looking at rook or queen",
    0x2D52:"check if we've each played 6 or fewer moves",
    0x2D54:"to penalise early moves of heavy pieces",
    0x2D59:"king-check entry point",
    0x2D5B:"bit 4 = has castled flag",
    0x2D5D:"king hasn't castled: penalise if moved",
    0x2D5F:"+6 for castled king",
    0x2D63:"get colour",
    0x2D65:"white: add the +6",
    0x2D67:"black: add -6 (will be negated)",
    0x2D69:"(effectively a JMP)",
    0x2D6F:"no penalty",
    0x2D71:"to apply the -2 penalty",
    0x2D73:"knight or bishop development",
    0x2D75:"bit 3 = has-moved flag",
    0x2D77:"already moved: no penalty",
    0x2D79:"-2 penalty for undeveloped knight/bishop or (via jump in) early-move heavy piece",
    0x2D7D:"check colour",
    0x2D7F:"white: add -2",
    0x2D81:"black: add +2 (will be negated)",
    0x2D85:"positional += bonus/penalty",
    0x2D8F:"load the just-generated attack count",
    0x2D93:"subtract defender count",
    0x2D97:"adjust the positional score accordingly",
    0x2D99:"(doubles as a mobility/pressure count over the board)",
    0x2D9B:"is this square occupied?",
    0x2DA7:"0 = piece is adequately defended / safe",
    0x2DA9:"checks if exchange evaluator said piece is safe or lost (?)",
    0x2DAB:"if non-0, piece hangs, decrement piece value by 1",
    0x2DAF:"is the hanging piece the same colour as the side to move?",
    0x2DB3:"different colour (opponent's piece hangs): jump to track attack values (?)",
    0x2DB5:"same colour (our piece hangs): track as best capture target (?)",
    0x2DB7:"highest static-exchange value seen so far",
    0x2DBB:"update it",
    0x2DC1:"is hanging piece on the destination square of the move being evaluated?",
    0x2DC5:"if yes, signal the piece we're moving will be under threat",
    0x2DDB:"load doubled piece value from exchange evaluator",
    0x2DDD:"bring colour in to sign bit",
    0x2DDF:"white: add normally",
    0x2DE1:"black: negate",
    0x2DE7:"material += value",
    0x2DEB:"next square",
    0x2DF0:"reached end of board yet?",
    0x2DF7:"if the move target hangs",
    0x2DFB:"promote 2nd-highest attack to highest (focus on the main threat) (?)",
    0x2E03:"best capture value",
    0x2E0C:"highest attack",
    0x2E10:"second-highest attack",
    0x2E17:"halve the secondary threat",
    0x2E19:"attack_score = half secondary - best capture",
    0x2E25:"attack_score + material",
    0x2E28:"subtract parent node's material",
    0x2E2A:"to get material difference",
    0x2E2E:"clamp material difference to +/- 30",
    0x2E31:"store clamped material difference",
    0x2E33:"positional difference = positional - parent's positional",
    0x2E36:"- best_so_far_positional (?)",
    0x2E38:"positional_diff (?)",
    0x2E3A:"if the move target hangs,",
    0x2E40:"zero out the positional diff (material concerns dominate when your piece is en prise)",
    0x2E44:"clamp positional difference to +/-6",
    0x2E47:"store clamped positional difference",
    0x2E49:"material difference",
    0x2E4C:"multiply it by 4",
    0x2E4D:"because material dominates",
    0x2E4F:"then add in positional difference",
    0x2E51:"score is in white-minus-black so convert to perspective of side to move",
    0x2E53:"black to move, parent was white, white-minus-black is already correct",
    0x2E55:"white to move, parent was black, negate",
    0x2E5B:"bias +128 to make score unsigned (0-255 range)",
    0x2E5D:"final score stored in $73",
    0x2E61:"and written into byte 5 of the move record",
    0x2E64:"static exchange evaluator",
    0x2E6C:"($80,$81) -> $10AC white per-type attack counts",
    0x2E70:"($82,$83) -> $10B3 black per-type attack counts",
    0x2E74:"which colour is the piece on this square?",
    0x2E76:"white piece: $85 = white counts (defenders), $84 = black counts (attackers)",
    0x2E78:"black piece: swap",
    0x2E90:"piece value is stored at $1025 + piece type",
    0x2E92:"($97 was set to $10 on init by $1C19)",
    0x2E94:"double it: this is the prize for capturing",
    0x2E95:"store current attacker threshold (?)",
    0x2E97:"seed the exchange with the defender's piece value",
    0x2E9C:"if someone can capture, continue (?)",
    0x2E9E:"nobody can capture: piece is safe, $62 stays 0 (?)",
    0x2EA8:"doubled piece value (?)",
    0x2EAA:"compare with attacker value (?)",
    0x2EAC:"piece value >= attacker, capture is safe (?)",
    0x2EE5:"get next cheapest attacker/defender (alternates colour each call)",
    0x2EE7:"swap $84/$85",
    0x2EE9:"so we alternate attacker/defender",
    0x2EF0:"flip X to point at the other colour's count array",
    0x2EF5:"any pieces left for this colour?",
    0x2EF7:"if no, return Z=1 as no more captures possible",
    0x2EFB:"scan per-type bytes to find a non-zero entry (cheapest first: pawn, knight, etc)",
    0x2F01:"packed byte: lower nibble = 1st piece value, upper nibble = 2nd piece value",
    0x2F04:"extract upper nibble (2nd attacker)",
    0x2F08:"and store back",
    0x2F0B:"return lower nibble = piece value of the attacker we just consumed",
    0x2F10:"double it (values are stored doubled throughout the exchange)",
    0x2F12:"clamp $65 to +/- A",
    0x2F1F:"return the clamped value",
    0x2F64:"write 1-8 rank legends on vertical sides of board",
    0x2FCA:"print $61 at X,Y",
    0x2FCF:"effectively JMP oswrch",
    0x2FD1:"cursor to X,Y",
    0x2FDE:"write a-h file legend at row Y",
    0x2FE3:"'a'",
    0x2FF8:"possibly a programmer's signature (or 8x8 sprite?)",
    0x3000:"Start of Mode 1 screen memory after relocation. This is where the disk version added its relocator loop.",
    0x3002:"It starts by doing the equivalent of *TAPE",
    0x3004:"to disable the DFS/ADFS:",
    0x300F:"relocating to $E00",
    0x3013:"relocating from $1E00",
    0x3026:"stop before source address $4000 (relocated address $3000)",
    0x302A:"This code copies 48 bytes into the cassette workspace at 3B0.  Since this is never read by the Chess program, I assume whoever wrote the disk relocator thought they'd better restore the CFS state as well just in case.  Almost certainly unnecessary.",
    0x302C:"$3050 in our relocated addresses",
    0x302F:"cassette BPUT workspace",
    0x3033:"stop at 48 bytes",
    0x3037:"*FX200 (apparently to",
    0x3039:"reset Break and Escape to normal",
    0x303B:"in case the BASIC loader set them differently)",
    0x3040:"flush buffers",
    0x3048:"padding (the relocator author didn't sign like someone apparently did at 2FF8)",
    0x3050:"these 48 bytes are copied to 3B0 (unnecessarily I think, see above)",
    0xFFE0:"osrdch (read character)",
    0xFFEE:"oswrch (write character)",
    0xFFF4:"osbyte (*FX)",
}

OPCODES = {
    0x00:("BRK",0),0x01:("ORA",8),0x05:("ORA",1),0x06:("ASL",1),
    0x08:("PHP",0),0x09:("ORA",11),0x0A:("ASL",12),0x0D:("ORA",4),
    0x0E:("ASL",4),0x10:("BPL",10),0x11:("ORA",9),0x15:("ORA",2),
    0x16:("ASL",2),0x18:("CLC",0),0x19:("ORA",6),0x1D:("ORA",5),
    0x1E:("ASL",5),0x20:("JSR",4),0x24:("BIT",1),0x25:("AND",1),
    0x26:("ROL",1),0x28:("PLP",0),0x29:("AND",11),0x2A:("ROL",12),
    0x2C:("BIT",4),0x2D:("AND",4),0x2E:("ROL",4),0x30:("BMI",10),
    0x31:("AND",9),0x35:("AND",2),0x36:("ROL",2),0x38:("SEC",0),
    0x39:("AND",6),0x3D:("AND",5),0x3E:("ROL",5),0x40:("RTI",0),
    0x41:("EOR",8),0x45:("EOR",1),0x46:("LSR",1),0x48:("PHA",0),
    0x49:("EOR",11),0x4A:("LSR",12),0x4C:("JMP",4),0x4D:("EOR",4),
    0x4E:("LSR",4),0x50:("BVC",10),0x51:("EOR",9),0x55:("EOR",2),
    0x56:("LSR",2),0x58:("CLI",0),0x59:("EOR",6),0x5D:("EOR",5),
    0x5E:("LSR",5),0x60:("RTS",0),0x61:("ADC",8),0x65:("ADC",1),
    0x66:("ROR",1),0x68:("PLA",0),0x69:("ADC",11),0x6A:("ROR",12),
    0x6C:("JMP",7),0x6D:("ADC",4),0x6E:("ROR",4),0x70:("BVS",10),
    0x71:("ADC",9),0x75:("ADC",2),0x76:("ROR",2),0x78:("SEI",0),
    0x79:("ADC",6),0x7D:("ADC",5),0x7E:("ROR",5),0x81:("STA",8),
    0x84:("STY",1),0x85:("STA",1),0x86:("STX",1),0x88:("DEY",0),
    0x8A:("TXA",0),0x8C:("STY",4),0x8D:("STA",4),0x8E:("STX",4),
    0x90:("BCC",10),0x91:("STA",9),0x94:("STY",2),0x95:("STA",2),
    0x96:("STX",3),0x98:("TYA",0),0x99:("STA",6),0x9A:("TXS",0),
    0x9D:("STA",5),0xA0:("LDY",11),0xA1:("LDA",8),0xA2:("LDX",11),
    0xA4:("LDY",1),0xA5:("LDA",1),0xA6:("LDX",1),0xA8:("TAY",0),
    0xA9:("LDA",11),0xAA:("TAX",0),0xAC:("LDY",4),0xAD:("LDA",4),
    0xAE:("LDX",4),0xB0:("BCS",10),0xB1:("LDA",9),0xB4:("LDY",2),
    0xB5:("LDA",2),0xB6:("LDX",3),0xB8:("CLV",0),0xB9:("LDA",6),
    0xBA:("TSX",0),0xBC:("LDY",5),0xBD:("LDA",5),0xBE:("LDX",6),
    0xC0:("CPY",11),0xC1:("CMP",8),0xC4:("CPY",1),0xC5:("CMP",1),
    0xC6:("DEC",1),0xC8:("INY",0),0xC9:("CMP",11),0xCA:("DEX",0),
    0xCC:("CPY",4),0xCD:("CMP",4),0xCE:("DEC",4),0xD0:("BNE",10),
    0xD1:("CMP",9),0xD5:("CMP",2),0xD6:("DEC",2),0xD8:("CLD",0),
    0xD9:("CMP",6),0xDD:("CMP",5),0xDE:("DEC",5),0xE0:("CPX",11),
    0xE1:("SBC",8),0xE4:("CPX",1),0xE5:("SBC",1),0xE6:("INC",1),
    0xE8:("INX",0),0xE9:("SBC",11),0xEA:("NOP",0),0xEC:("CPX",4),
    0xED:("SBC",4),0xEE:("INC",4),0xF0:("BEQ",10),0xF1:("SBC",9),
    0xF5:("SBC",2),0xF6:("INC",2),0xF8:("SED",0),0xF9:("SBC",6),
    0xFD:("SBC",5),0xFE:("INC",5)
}

def format_operand(mem,addr,mode):
    if mode==1: return f"${mem[addr+1]:02X}",2 # ZP
    elif mode==2: return f"${mem[addr+1]:02X},X",2 # ZP,X
    elif mode==3: return f"${mem[addr+1]:02X},Y",2 # ZP,Y
    elif mode==4: return f"${mem[addr+2]:02X}{mem[addr+1]:02X}",3 # ABS
    elif mode==5: return f"${mem[addr+2]:02X}{mem[addr+1]:02X},X",3 # ABS,X
    elif mode==6: return f"${mem[addr+2]:02X}{mem[addr+1]:02X},Y",3 # ABS,Y
    elif mode==7: return f"(${mem[addr+2]:02X}{mem[addr+1]:02X})",3 # IND
    elif mode==8: return f"(${mem[addr+1]:02X},X)",2 # (ZP,X)
    elif mode==9: return f"(${mem[addr+1]:02X}),Y",2 # (ZP),Y
    elif mode==10: # Relative
        offset = mem[addr+1]
        if offset > 127: offset -= 256
        target = (addr + 2 + offset) & 0xFFFF
        return f"${target:04X}",2
    elif mode==11: return f"#${mem[addr+1]:02X}",2 # Immediate
    elif mode==12: return "A",1 # Accumulator
    else: return "",1 # mode 0 implied

def disasm(mem):
    queue = [entryPoint]
    visited = set()
    code_lines = {}
    while queue:
        addr = queue.pop(0)
        if addr in visited or addr >= len(mem): continue
        op = mem[addr]
        if op in OPCODES: name,mode = OPCODES[op]
        else:
            print("Warning: code ran into unrecognised opcode at",hex(addr))
            continue
        operand,length = format_operand(mem,addr,mode)
        for L in range(length): visited.add(addr+L)
        hex_bytes = " ".join(f"{mem[addr+i]:02X}" for i in range(length))
        code_lines[addr] = f"${addr:04X}: {hex_bytes:<10} {name} {operand}".rstrip()
        # Add targets to queue
        if name in ("JMP","JSR") and mode==4: # Absolute
            target = mem[addr+2] << 8 | mem[addr+1]
            if target < 0xFF00: queue.append(target)
            if target in comments:
                code_lines[addr] += " ; "+name+" "+comments[target]
            
            # Special case: JSR $1D95 is the inline string printer
            # The next bytes are string data until we find top bit set
            if target==0x1D95:
                string_start = addr + 3
                string_end = string_start
                while (mem[string_end] & 0x80)==0:
                    visited.add(string_end)
                    string_end += 1
                queue.append(string_end) # the terminator itself is the next instruction (will be 0xEA NOP if the actual next instruction is <128)
                code_lines[addr] += f" with data {repr(mem[string_start:string_end])[len('bytearray(b'):-1]}"
                if mem[string_end]==0xEA and string_end not in comments: comments[string_end]="terminator for data"
                continue
        elif name in ("BPL","BMI","BVC","BVS","BCC","BCS","BNE","BEQ"): # Relative
            offset = mem[addr+1]
            if offset > 127: offset -= 256
            target = (addr + 2 + offset) & 0xFFFF
            queue.append(target)
        if not name in ["JMP","RTS"]: queue.append(addr + length)
    for missed in range(loadTo,len(mem)):
        if not missed in visited:
            missedEnd = missed
            while not missedEnd in visited and missedEnd<len(mem) and not (missedEnd>missed and (missedEnd%16==0 or missedEnd in comments)):
                visited.add(missedEnd)
                missedEnd += 1
            code_lines[missed] = f"${missed:04X}: data {repr(mem[missed:missedEnd])[len('bytearray(b'):-1].replace(chr(0x22),chr(0x5c)+'x22')}" # the .replace here is to be nice to Emacs' syntax highlighter in the .asm
    for addr,comment in list(comments.items()):
        if addr in code_lines:
            code_lines[addr] += " ; "+comment
        else: assert addr >= 0xFF00, "comment for unknown address "+hex(addr)
    return code_lines

if __name__=="__main__": main()
